name: CI Pipeline

on:
  workflow_run:
    workflows: [CD Pipeline]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Zip Lambda code
        run: |
          cd lambda/src
          zip -r ../../lambda-poc5.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: |
          aws s3 cp lambda-poc5.zip s3://${{ secrets.LAMBDA_BUCKET_NAME }}/lambda-poc5.zip